fix: make govcloud builds possible (#2621)
Make various fixes so that govcloud builds work:

* Make latest-binaries.sh handle fetching cross-partition
* Change s3 copy logic to not check the AWS_ACCESS_KEY_ID variable,
  which is a fundamentally flawed check, and instead just attempt a copy
  using the environment's credentials and fall back to --no-sign-request
  if the initial copy fails.
* update the cache-pause-container script to use the eks-distro public mirror

The net effect of this change is that by default, none of the
provisioners rely on the caller's AWS credentials. I'm leaving in the
logic that passes through the AWS credentials via environment variables
since removing is a breaking change, but none of them are needed.

In a future major release, it would be nice to remove those entirely and
require people to use instance roles if they need permissions from the
provisioners (e.g. for private artifact buckets).

diff --git a/templates/shared/runtime/bin/cache-pause-container b/templates/shared/runtime/bin/cache-pause-container
--- a/templates/shared/runtime/bin/cache-pause-container
+++ b/templates/shared/runtime/bin/cache-pause-container
@@ -23,6 +23,12 @@ done
 PULL_ARGS=""
 if [[ "${PAUSE_CONTAINER_IMAGE}" == *"dkr.ecr"* ]]; then
   PULL_ARGS="${PULL_ARGS} --user AWS:$(aws ecr get-login-password)"
+elif [[ "${PAUSE_CONTAINER_IMAGE}" == *"public.ecr.aws"* ]]; then
+  if ECR_PUBLIC_PASSWORD=$(aws ecr-public get-login-password); then
+    PULL_ARGS="${PULL_ARGS} --user AWS:${ECR_PUBLIC_PASSWORD}"
+  else
+    echo "Failed to authenticate to public ECR, retrying with unauthenticated pull" >&2
+  fi
 fi
 sudo ctr --namespace k8s.io image pull ${PULL_ARGS} ${PAUSE_CONTAINER_IMAGE}
 sudo ctr --namespace k8s.io image tag ${PAUSE_CONTAINER_IMAGE} ${TAG}
