Update .github/actions/ci/build/action.yaml

diff --git a/.github/actions/ci/build/action.yaml b/.github/actions/ci/build/action.yaml
--- a/.github/actions/ci/build/action.yaml
+++ b/.github/actions/ci/build/action.yaml
@@ -27,17 +27,16 @@ runs:
     - id: build
       shell: bash
       run: |
-        exit_code=0
+        ECR_MISSING_REGION="false"
         ECR_SCRIPT_PATH=templates/al2/runtime/get-ecr-uri.sh
-        for region in $(aws account list-regions| jq '.Regions[].RegionName' -r); do
-            if ! grep -q $region $ECR_SCRIPT_PATH; then
-            echo "missing ECR account for $region in $ECR_SCRIPT_PATH"
-            exit_code=1
-            fi
+        for REGION in $(aws account list-regions | jq -r '.Regions[].RegionName'); do
+          if ! grep -q "${REGION}" "${ECR_SCRIPT_PATH}"; then
+            echo >&2 "ERROR: missing account for ${REGION} in ${ECR_SCRIPT_PATH}"
+            ECR_MISSING_REGION="true"
+          fi
         done
-
-        if (($exit_code)); then
-            exit $exit_code;
+        if [ "$ECR_MISSING_REGION" = "true" ]; then
+          exit 1
         fi
 
         PACKER_GITHUB_API_TOKEN="${{ github.token }}" packer plugins install github.com/hashicorp/amazon
